language: python
python:
- 3.6
install:
- pip install sphinx sphinx_rtd_theme sphinx-argparse recommonmark

scripts:
- echo "Generating documentation..."
- cd docs/sources
- make html
- cd ../build/all/html
- touch .nojekyll
- cd ../../../../